server:
  port: 8000

zuul:
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie,Authorization
  retryable: true
  routes:
    oauth2-server:
      path: /uaa/**
      service-id: oauth2-server
      strip-prefix: false
    user-service:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    address-service:
      path: /addresses/**
      service-id: address-service
      strip-prefix: false
    point-service:
      path: /points/**
      service-id: point-service
      strip-prefix: false
    product-service:
      path: /products/**
      service-id: product-service
      strip-prefix: false
    order-service:
      path: /orders/**
      service-id: order-service
      strip-prefix: false
    payment-service:
      path: /payments/**
      service-id: payment-service
      strip-prefix: false
    delivery-service:
      path: /deliveries/**
      service-id: delivery-service
      strip-prefix: false

logging:
  level:
    org.springframework.security: DEBUG

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: /users/activation,/uaa/oauth/token/**

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 80000