spring:
  application:
    name: eureka
  profiles:
    active: development

management:
  security:
    enabled: false

---
spring:
  profiles: development

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 10

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_2_SERVICE_HOST}:${EUREKA_2_SERVICE_PORT}/eureka/
  server:
    enable-self-preservation: false

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_1_SERVICE_HOST}:${EUREKA_1_SERVICE_PORT}/eureka/
  server:
    enable-self-preservation: false